### PR TITLE
Restructured the project so it can be used as a library in other progams as well

### PR DESCRIPTION
**Pull request by schoentoon**
When I initially ran in this program I quickly got excited about what I could do with it inside some of my own internal tools. Only to realize everything was just in a single main.go file. So I figured I would split all of the logic into a separate file/library so it can easily be reused in other programs. The main binary as you're used to it is now in ./cmd/imgcat instead, this may require some adjusting to goreleaser.

### CODE REVIEW

**Comment by trashhalo** [comment]
Too funny. Was just talking about doing that as part of #11 

Thanks for the pr! Ill take a look at the goreleaser stuff to make sure it will work before merging.

**Comment by schoentoon** [comment]
Lmao, I didn't even see that issue honestly. Good to see that you and others seem to agree that this should probably be a library.

**Comment by muesli** [comment]
> The main binary as you're used to it is now in ./cmd/imgcat instead, this may require some adjusting to goreleaser.

Indeed! Luckily it's really straightforward. Keep the `.goreleaser.yml` in the root of the repo and add the following setting to its build section:

```
    dir: ./cmd/imgcat
```

You can find an example for this in https://github.com/charmbracelet/charm/blob/master/.goreleaser.yml

**Comment by trashhalo** [comment]
Ah! Perfect. I pulled the branch down and tried to run goreleaser and it said:
```shell
  ⨯ release failed after 1.84s error=build for imgcat does not contain a main function
```

**Comment by schoentoon** [comment]
Added `dir: ./cmd/imgcat`.. Tried to test it but goreleaser kept bitching about all kinds of missing variables and what not (exactly why I don't like this tool at all tbh).

**Comment by trashhalo** [comment]
```sh
   • release succeeded after 80.86s
```
TADA!

**Comment by trashhalo** [comment]
PR merged. Im going to hold off on cutting a release til your second pr comes in.

**Comment by schoentoon** [comment]
Could you consider opting into [hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update)? :)

**Comment by trashhalo** [comment]
okay I think I did the things! to make hacktoberfest work

**Comment by muesli** [comment]
@trashhalo You can add the `hacktoberfest` label/topic to the entire repo, then all PRs will automatically count.

**Pull request merged**
